### ISSUE TITLE
Add soft min/max flow to LinkNode

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr-next#181]
Feature request to add ability for a soft minimum and/or maximum node. This feature could be added to the basic node types: Input, Link and Output. When active it would create an additional internal node for the soft min and/or max.

**Comment by s-simoncelli** [comment]
I started to implement this for a `Link` node. Do we want the node to look like this internally? 

<img width="369" alt="image" src="https://github.com/pywr/pywr-next/assets/16114781/1786c628-214c-4583-99c2-9ab9147027ae">

Or is it simpler to just set one soft constraint and the user decides whether it is a min or max?

**Comment by jetuk** [comment]
I think the schematic is correct. I think you'll want it to only create the additional links if they are needed. It will probably be easier to keep them separated/dedicated for min and max for clarity and tracking (also if someone wants both?).

We'll need to ensure that the attributes correctly reflect these additional links.

**Comment by s-simoncelli** [comment]
Ok, my first implementation is in #213

**Comment by jetuk** [comment]
Completed in #213
