### ISSUE TITLE
Cannot compile 

### ISSUE THREAD

**Issue by s-simoncelli** [pywr/pywr-next#214]
Hello,

I have been having issues compiling the `coin-or-sys` crate:
      
      cargo:warning=In file included from vendor/Clp/src/OsiClp/OsiClpSolverInterface.cpp:31:
      cargo:warning=vendor/Clp/src/OsiClp/OsiClpSolverInterface.hpp:15:10: fatal error: 'OsiSolverInterface.hpp' file not found
      cargo:warning=#include "OsiSolverInterface.hpp"

The header file is not in the vendor folder.

**Comment by jetuk** [comment]
Try running `git submodule update`. #208 added some new submodules.

**Comment by s-simoncelli** [comment]
Thanks, I had to use

    git submodule update --init

to fetch all nested submodules instead
